name: ebook
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  cupertino_tabbar: ^2.0.0
  animated_text_kit: ^4.2.2
  http: ^0.13.3
  crypto: ^3.0.1
  url_launcher: ^6.0.9
  photo_view: ^0.14.0
  shared_preferences: ^2.0.6
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  quickalert: ^1.0.1
  riverpod: ^2.3.6
  flutter_riverpod: ^2.3.6
  google_fonts: ^4.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
   uses-material-design: true
   assets:
    - assets/images/

   fonts:
     - family: bungee
       fonts:
         - asset: assets/fonts/Bungee-Regular.ttf
